/**
 * EXTROVELA — Quest Engine Candidate Generator
 * 
 * Generates a pool of 15–30 candidate quests from a high-quality curated seed library
 * across thematic categories and experiential patterns.
 */

import { EngineContext, QuestCandidate } from '../types';

export const SEED_QUEST_TEMPLATES: Omit<QuestCandidate, 'id'>[] = [
  {
    title: 'Chase the Last Light',
    description: 'Walk toward an open viewpoint or rooftop you have never stood on before. Watch the sky shift from gold to deep indigo without touching your phone.',
    category: 'Nature & Mindfulness',
    environment: 'Outdoor',
    mood: 'Reflective',
    energy: 'Chill',
    time: '1 hour',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'nature_sunset_viewpoint_solo',
    tags: ['sunset', 'mindful', 'viewpoint'],
  },
  {
    title: 'The 15-Minute Secret Alley Walk',
    description: 'Step outside immediately. Turn left at the first intersection you usually ignore. Walk until you notice a hidden doorway, stone carving, or peaceful courtyard.',
    category: 'Exploration',
    environment: 'Outdoor',
    mood: 'Curious',
    energy: 'Moderate',
    time: '15 mins',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'exploration_alley_walk_solo',
    tags: ['micro_escape', 'curiosity'],
  },
  {
    title: 'Analog Teahouse Sanctuary',
    description: 'Find a traditional street teahouse. Order a warm spiced chai, sit down, and listen to the ambient chatter for 20 minutes without checking notifications.',
    category: 'Quiet Sanctuary',
    environment: 'Indoor',
    mood: 'Peaceful',
    energy: 'Chill',
    time: '30 mins',
    budget: 'Low ($)',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'sanctuary_teahouse_chai_solo',
    tags: ['chai', 'mindful', 'analog'],
  },
  {
    title: 'The One-Color Photography Hunt',
    description: 'Pick the color amber or emerald. Walk 500 meters and photograph 3 unique real-world objects that share that color.',
    category: 'Creative',
    environment: 'Outdoor',
    mood: 'Curious',
    energy: 'Moderate',
    time: '30 mins',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Stretch',
    fingerprint: 'creative_photo_colorhunt_solo',
    tags: ['photography', 'creative'],
  },
  {
    title: 'Silent Hilltop Cloud Watching',
    description: 'Find a grassy hilltop or open terrace with a broad horizon. Lie back or sit comfortably for 15 minutes observing the drifting cloud shapes.',
    category: 'Nature & Mindfulness',
    environment: 'Outdoor',
    mood: 'Peaceful',
    energy: 'Chill',
    time: '30 mins',
    budget: 'Free',
    social: 'Solo',
    season: 'Garimahina (Summer)',
    difficulty: 'Comfort',
    fingerprint: 'nature_cloudgazing_solo',
    tags: ['nature', 'clouds', 'mindful'],
  },
  {
    title: 'Courtyard Architecture Sketch / Note',
    description: 'Find an ancient brick courtyard. Sit on a stone ledge and jot down or sketch 3 architectural details you would normally walk past without noticing.',
    category: 'Creative',
    environment: 'Outdoor',
    mood: 'Reflective',
    energy: 'Chill',
    time: '30 mins',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'creative_courtyard_sketch_solo',
    tags: ['heritage', 'sketch', 'observation'],
  },
  {
    title: 'The Unplanned Bus Terminus Adventure',
    description: 'Board the first local micro-bus or tempo you see. Ride it all the way to its final stop. Walk for 20 minutes in that neighborhood before returning.',
    category: 'Exploration',
    environment: 'Outdoor',
    mood: 'Spontaneous',
    energy: 'High Energy',
    time: '2+ hours',
    budget: 'Low ($)',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Adventure',
    fingerprint: 'exploration_bus_terminus_adventure',
    tags: ['transit', 'discovery', 'adventure'],
  },
  {
    title: 'Low-Pressure Teahouse Sincere Compliment',
    description: 'Visit a small local bakery or teahouse. Pay sincere attention to their craft and give one genuine compliment to the person preparing your order.',
    category: 'Low-Pressure Social',
    environment: 'Indoor',
    mood: 'Social',
    energy: 'Chill',
    time: '30 mins',
    budget: 'Low ($)',
    social: 'Low-pressure social',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'social_compliment_teahouse',
    tags: ['social', 'kindness', 'connection'],
  },
  {
    title: 'Rainy Day Bookstore Sanctuary',
    description: 'Enter an independent local bookstore. Pick a section you have never browsed before (e.g. poetry or philosophy). Read 15 pages in silence.',
    category: 'Quiet Sanctuary',
    environment: 'Indoor',
    mood: 'Peaceful',
    energy: 'Chill',
    time: '1 hour',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'sanctuary_bookstore_reading_solo',
    tags: ['books', 'reading', 'indoor'],
  },
  {
    title: 'The Night Lights Stroll',
    description: 'Walk through a well-lit street after dusk. Focus entirely on the reflections of lanterns, vehicle lights, and shop signs without looking at your notifications.',
    category: 'Mindfulness & Viewpoints',
    environment: 'Outdoor',
    mood: 'Reflective',
    energy: 'Moderate',
    time: '30 mins',
    budget: 'Free',
    social: 'Solo',
    season: 'Any',
    difficulty: 'Comfort',
    fingerprint: 'mindfulness_night_stroll_solo',
    tags: ['night', 'lights', 'stroll'],
  },
];

export class CandidateGenerator {
  static generateCandidates(_context: EngineContext): QuestCandidate[] {
    return SEED_QUEST_TEMPLATES.map((tpl, idx) => ({
      ...tpl,
      id: `candidate_${Date.now()}_${idx}`,
    }));
  }
}
