/**
 * EXTROVELA — Smart Collection Rules (Phase 12) — PURE, no Firebase, no network.
 *
 * A smart collection's membership is computed here, on-device, from a declarative
 * rule over the user's own memories. There is no LLM and no hidden scoring: a
 * clause either matches a memory or it does not, and the user can read the rule.
 * This is what lets the UI say, truthfully, "these are here because they are
 * outdoor experiences" rather than "the algorithm chose these".
 */

import { Memory } from '../../types/memory';
import { SmartCollectionRule, SmartRuleClause } from '../../types/collections';

const OUTDOOR_TAGS = ['outdoor', 'nature', 'scenic', 'sunset', 'hike'];
const INDOOR_TAGS = ['indoor', 'sanctuary', 'teahouse', 'cafe'];

function tagsOf(m: Memory): string[] {
  return (m.tags || []).map(t => t.toLowerCase());
}

/** Whether a single memory satisfies a single clause. */
export function matchesClause(memory: Memory, clause: SmartRuleClause): boolean {
  const value = (clause.value || '').toLowerCase().trim();
  switch (clause.field) {
    case 'tag':
      return !!value && tagsOf(memory).includes(value);
    case 'category':
      return !!value && (memory.category || '').toLowerCase() === value;
    case 'city':
      return !!value && (memory.location?.city || '').toLowerCase() === value;
    case 'mood':
      return !!value && (memory.mood || '').toLowerCase() === value;
    case 'favorite':
      return memory.isFavorite === true;
    case 'firstTime':
      return memory.isFirstTimeExperience === true || memory.firstTimeFlags?.newPlace === true;
    case 'outdoor':
      return OUTDOOR_TAGS.some(t => tagsOf(memory).includes(t));
    case 'indoor':
      return INDOOR_TAGS.some(t => tagsOf(memory).includes(t));
    default:
      return false;
  }
}

/** The memory ids that belong to a smart collection, in the memories' own order. */
export function evaluateSmartCollection(rule: SmartCollectionRule, memories: Memory[]): string[] {
  if (!rule || !Array.isArray(rule.clauses) || rule.clauses.length === 0) return [];
  return memories
    .filter(m => {
      const results = rule.clauses.map(c => matchesClause(m, c));
      return rule.match === 'all' ? results.every(Boolean) : results.some(Boolean);
    })
    .map(m => m.id);
}

/**
 * Starter smart collections offered to every user. Each is fully described by its
 * rule — nothing here is generated by a model.
 */
export const PREDEFINED_SMART_COLLECTIONS: { key: string; name: string; icon: string; rule: SmartCollectionRule }[] = [
  { key: 'first-times', name: 'First-Times', icon: '✨', rule: { match: 'any', clauses: [{ field: 'firstTime' }] } },
  { key: 'favorites', name: 'Favorites', icon: '★', rule: { match: 'any', clauses: [{ field: 'favorite' }] } },
  { key: 'outdoors', name: 'Outdoor Adventures', icon: '🌿', rule: { match: 'any', clauses: [{ field: 'outdoor' }] } },
  { key: 'sanctuaries', name: 'Quiet Sanctuaries', icon: '☕', rule: { match: 'any', clauses: [{ field: 'indoor' }] } },
  { key: 'sunsets', name: 'Sunsets', icon: '🌇', rule: { match: 'any', clauses: [{ field: 'tag', value: 'sunset' }] } },
];
